FROM node:alpine as server-build

WORKDIR /var/www/api.localhost

COPY ./server/package.json  ./package.json
# install production dependencies with npm run
RUN yarn 

COPY  ./server  /var/www/api.localhost
# build 
RUN yarn build
# Set environment variables
ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000
CMD [ "node", "/var/www/api.localhost/dist/index.js" ]
